In [1]:
import pandas as pd
from os.path import join, basename

In [2]:
indir = "/home/lhvu/bio/1000-vcf/vcf"

In [3]:
idfile = join(indir, "Coriell-Catalog-Export-06-16-2025.csv")

In [4]:
df = pd.read_csv(idfile)

In [5]:
df.head()

        ID                        Description Product        Source
0  HG02070  KINH IN HO CHI MINH CITY, VIETNAM     LCL  B-Lymphocyte
1  HG01849  KINH IN HO CHI MINH CITY, VIETNAM     LCL  B-Lymphocyte
2  HG01874  KINH IN HO CHI MINH CITY, VIETNAM     LCL  B-Lymphocyte
3  HG01599  KINH IN HO CHI MINH CITY, VIETNAM     LCL  B-Lymphocyte
4  HG02525  KINH IN HO CHI MINH CITY, VIETNAM     LCL  B-Lymphocyte

In [6]:
df.shape

(124, 4)

In [7]:
ids = list(df['ID'].values)

In [8]:
ids

['HG02070',
 'HG01849',
 'HG01874',
 'HG01599',
 'HG02525',
 'HG02015',
 'HG01872',
 'HG02121',
 'HG02083',
 'HG02078',
 'HG02128',
 'HG02045',
 'HG02087',
 'HG02027',
 'HG01846',
 'HG02113',
 'HG02088',
 'HG02126',
 'HG02140',
 'HG02086',
 'HG02023',
 'HG01843',
 'HG02081',
 'HG01865',
 'HG01597',
 'HG01873',
 'HG02085',
 'HG02139',
 'HG01847',
 'HG02073',
 'HG02524',
 'HG01848',
 'HG02079',
 'HG02133',
 'HG02028',
 'HG01869',
 'HG02523',
 'HG02035',
 'HG02137',
 'HG02071',
 'HG02029',
 'HG01842',
 'HG02138',
 'HG02116',
 'HG02084',
 'HG02068',
 'HG02080',
 'HG01867',
 'HG02025',
 'HG02120',
 'HG01844',
 'HG01850',
 'HG02136',
 'HG02075',
 'HG01857',
 'HG01855',
 'HG02077',
 'HG02016',
 'HG01866',
 'HG02024',
 'HG02522',
 'HG02048',
 'HG02026',
 'HG02130',
 'HG01861',
 'HG01596',
 'HG02047',
 'HG02129',
 'HG01841',
 'HG02060',
 'HG01863',
 'HG02134',
 'HG02059',
 'HG02046',
 'HG02067',
 'HG02020',
 'HG01878',
 'HG02526',
 'HG02072',
 'HG01864',
 'HG01870',
 'HG02512',
 'HG02069',
 'HG01871',
 'HG02141',
 'HG02082',
 'HG02074',
 'HG01860',
 'HG02049',
 'HG02056',
 'HG02135',
 'HG01859',
 'HG01845',
 'HG02142',
 'HG02132',
 'HG02122',
 'HG01868',
 'HG02019',
 'HG01858',
 'HG02127',
 'HG02032',
 'HG02017',
 'HG02513',
 'HG02057',
 'HG02040',
 'HG02521',
 'HG02050',
 'HG02031',
 'HG01853',
 'HG02061',
 'HG01840',
 'HG02131',
 'HG01851',
 'HG02030',
 'HG02058',
 'HG01595',
 'HG02018',
 'HG01598',
 'HG02064',
 'HG01600',
 'HG02514',
 'HG01862',
 'HG01852',
 'HG02076']

In [9]:
elems = [f'-F {e}' for e in ids]

In [10]:
elems

['-F HG02070',
 '-F HG01849',
 '-F HG01874',
 '-F HG01599',
 '-F HG02525',
 '-F HG02015',
 '-F HG01872',
 '-F HG02121',
 '-F HG02083',
 '-F HG02078',
 '-F HG02128',
 '-F HG02045',
 '-F HG02087',
 '-F HG02027',
 '-F HG01846',
 '-F HG02113',
 '-F HG02088',
 '-F HG02126',
 '-F HG02140',
 '-F HG02086',
 '-F HG02023',
 '-F HG01843',
 '-F HG02081',
 '-F HG01865',
 '-F HG01597',
 '-F HG01873',
 '-F HG02085',
 '-F HG02139',
 '-F HG01847',
 '-F HG02073',
 '-F HG02524',
 '-F HG01848',
 '-F HG02079',
 '-F HG02133',
 '-F HG02028',
 '-F HG01869',
 '-F HG02523',
 '-F HG02035',
 '-F HG02137',
 '-F HG02071',
 '-F HG02029',
 '-F HG01842',
 '-F HG02138',
 '-F HG02116',
 '-F HG02084',
 '-F HG02068',
 '-F HG02080',
 '-F HG01867',
 '-F HG02025',
 '-F HG02120',
 '-F HG01844',
 '-F HG01850',
 '-F HG02136',
 '-F HG02075',
 '-F HG01857',
 '-F HG01855',
 '-F HG02077',
 '-F HG02016',
 '-F HG01866',
 '-F HG02024',
 '-F HG02522',
 '-F HG02048',
 '-F HG02026',
 '-F HG02130',
 '-F HG01861',
 '-F HG01596',
 '-F HG02047',
 '-F HG02129',
 '-F HG01841',
 '-F HG02060',
 '-F HG01863',
 '-F HG02134',
 '-F HG02059',
 '-F HG02046',
 '-F HG02067',
 '-F HG02020',
 '-F HG01878',
 '-F HG02526',
 '-F HG02072',
 '-F HG01864',
 '-F HG01870',
 '-F HG02512',
 '-F HG02069',
 '-F HG01871',
 '-F HG02141',
 '-F HG02082',
 '-F HG02074',
 '-F HG01860',
 '-F HG02049',
 '-F HG02056',
 '-F HG02135',
 '-F HG01859',
 '-F HG01845',
 '-F HG02142',
 '-F HG02132',
 '-F HG02122',
 '-F HG01868',
 '-F HG02019',
 '-F HG01858',
 '-F HG02127',
 '-F HG02032',
 '-F HG02017',
 '-F HG02513',
 '-F HG02057',
 '-F HG02040',
 '-F HG02521',
 '-F HG02050',
 '-F HG02031',
 '-F HG01853',
 '-F HG02061',
 '-F HG01840',
 '-F HG02131',
 '-F HG01851',
 '-F HG02030',
 '-F HG02058',
 '-F HG01595',
 '-F HG02018',
 '-F HG01598',
 '-F HG02064',
 '-F HG01600',
 '-F HG02514',
 '-F HG01862',
 '-F HG01852',
 '-F HG02076']

In [11]:
s =  ' '.join(elems)

In [12]:
s

'-F HG02070 -F HG01849 -F HG01874 -F HG01599 -F HG02525 -F HG02015 -F HG01872 -F HG02121 -F HG02083 -F HG02078 -F HG02128 -F HG02045 -F HG02087 -F HG02027 -F HG01846 -F HG02113 -F HG02088 -F HG02126 -F HG02140 -F HG02086 -F HG02023 -F HG01843 -F HG02081 -F HG01865 -F HG01597 -F HG01873 -F HG02085 -F HG02139 -F HG01847 -F HG02073 -F HG02524 -F HG01848 -F HG02079 -F HG02133 -F HG02028 -F HG01869 -F HG02523 -F HG02035 -F HG02137 -F HG02071 -F HG02029 -F HG01842 -F HG02138 -F HG02116 -F HG02084 -F HG02068 -F HG02080 -F HG01867 -F HG02025 -F HG02120 -F HG01844 -F HG01850 -F HG02136 -F HG02075 -F HG01857 -F HG01855 -F HG02077 -F HG02016 -F HG01866 -F HG02024 -F HG02522 -F HG02048 -F HG02026 -F HG02130 -F HG01861 -F HG01596 -F HG02047 -F HG02129 -F HG01841 -F HG02060 -F HG01863 -F HG02134 -F HG02059 -F HG02046 -F HG02067 -F HG02020 -F HG01878 -F HG02526 -F HG02072 -F HG01864 -F HG01870 -F HG02512 -F HG02069 -F HG01871 -F HG02141 -F HG02082 -F HG02074 -F HG01860 -F HG02049 -F HG02056 -F HG02135 -F HG01859 -F HG01845 -F HG02142 -F HG02132 -F HG02122 -F HG01868 -F HG02019 -F HG01858 -F HG02127 -F HG02032 -F HG02017 -F HG02513 -F HG02057 -F HG02040 -F HG02521 -F HG02050 -F HG02031 -F HG01853 -F HG02061 -F HG01840 -F HG02131 -F HG01851 -F HG02030 -F HG02058 -F HG01595 -F HG02018 -F HG01598 -F HG02064 -F HG01600 -F HG02514 -F HG01862 -F HG01852 -F HG02076'

In [13]:
vcffile = join(indir, "ALL.chr9.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.csv")

In [14]:
vdf = pd.read_csv(vcffile, sep='\t')

In [15]:
vdf.head()

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HG02070,...,HG02058,HG01595,HG02018,HG01598,HG02064,HG01600,HG02514,HG01862,HG01852,HG02076
0,9,10648,.,G,A,-10.0,PASS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9,10689,.,C,A,-10.0,PASS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,10690,.,G,A,-10.0,PASS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,10691,.,G,A,-10.0,PASS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,10709,.,G,A,-10.0,PASS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
meta_cols = ['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT']

In [17]:
vdf2 = vdf

In [18]:
vdf2.drop(columns=meta_cols, inplace=True)

In [19]:
vdf2.shape

(3384360, 124)

In [20]:
vdf.head()

,HG02070,HG01849,HG01874,HG01599,HG02525,HG02015,HG01872,HG02121,HG02083,HG02078,...,HG02058,HG01595,HG02018,HG01598,HG02064,HG01600,HG02514,HG01862,HG01852,HG02076
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Find columns with at least one non-NaN value
columns_with_non_nan = vdf.notna().any()

# Get the names of the columns with at least one non-NaN value
non_nan_columns = columns_with_non_nan[columns_with_non_nan].index

In [22]:
non_nan_columns

Index([], dtype='object')